title: "Lägenheten i Åre"
description: "Hyr vår mysiga lägenhet i Åre – nära backar, natur och restauranger."
url: ""  # Set your custom domain or leave empty for user.github.io/repo
baseurl: ""  # e.g. /the-apartment if not publishing to a user/organization site

# Minimal Mistakes configuration
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
# For GitHub Pages builds
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

locale: sv

markdown: kramdown
highlighter: rouge

# Author/profile
author:
  name: "Åre Apartment"
  avatar: "/assets/images/huset_nära.jpg"
  bio: "Perfekt bas för skidåkning, cykling och fjällhäng."
  location: "Åre, Jämtland, Sverige"

# Theme settings
logo: "/assets/images/huset_nära.jpg"
search: true
permalink: "/:categories/:title/"

# Navigation
collections:
  pages:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar: false

# Footer links (update as you wish)
footer:
  links:
    - label: "E-post"
      icon: "fas fa-envelope"
      url: "mailto:johan.kindgren@gmail.com"

# SEO
seo:
  type: "WebSite"
  name: "Lägenheten i Åre"
